resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
    instances:
      products:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 2s
    instances:
      products:
        base-config: defecto



spring:
  cloud:
    gateway:
      routes:
        - id: msvc-products
          uri: lb://msvc-products
          predicates:
            - Path=/api/a/**
          #- Path=/api/products/**
#            - Header=token, \d+
#            - Method=GET, POST
#            - Query=color, verde
#            - Cookie=colorPredicate, azul
#            - Header=Content-Type, application/json
          filters:
            - name: CircuitBreaker
              args:
                name: products
                statusCodes: 500, 404
                fallBackUri: forward:/api/b/items/find/5

            - StripPrefix=2
            - EjemploCookie=Hola mi mensaje personalizado para productos, user, Andres
            #- SampleCookie=Hola mi mensaje personalizado para productos, user, Andres
            #- name: SampleCookie
              #args:
                #message: Hola mi mensaje personalizado para productos
                #name: user
                #value: Andres
        - id: Microservicios-Cloud-Items
          uri: lb://Microservicios-Cloud-Items
          predicates:
            - Path=/api/b/**
          #- Path=/api/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request, token3wqertqyuiwowowowow
            - AddResponseHeader=token-response, token41223455
            - AddRequestParameter=name,Casse
            - SetResponseHeader=Content-Type, text/plain